DefaultContentLanguage = "es"
baseURL = "https://agencialetraherida.com/"
contacto = "hola@letraherida.com"
copyright = "© Copyright notice"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
theme = "eenyakee"
title = "Letraherida"
[languages.cat]
languageName = "Català"
languageNameShort = "cat"
weight = 3
[[languages.cat.menu.main]]
name = "Serveis"
url = "#servicios"
weight = 1
[[languages.cat.menu.main]]
name = "Manifest"
url = "#manifiesto"
weight = 2
[[languages.cat.menu.main]]
name = "Som"
url = "#somos"
weight = 3
[[languages.cat.menu.main]]
name = "Clients"
url = "#clientes"
weight = 4
[languages.en]
languageName = "English"
languageNameShort = "eng"
weight = 2
[[languages.en.menu.main]]
name = "Services"
url = "#servicios"
weight = 1
[[languages.en.menu.main]]
name = "Manifest"
url = "#manifiesto"
weight = 2
[[languages.en.menu.main]]
name = "We are"
url = "#somos"
weight = 3
[[languages.en.menu.main]]
name = "Clients"
url = "#clientes"
weight = 4
[languages.es]
languageName = "Español"
languageNameShort = "es"
weight = 1
[[languages.es.menu.main]]
name = "Servicios"
url = "#servicios"
weight = 1
[[languages.es.menu.main]]
name = "Manifiesto"
url = "#manifiesto"
weight = 2
[[languages.es.menu.main]]
name = "Somos"
url = "#somos"
weight = 3
[[languages.es.menu.main]]
name = "Clientes"
url = "#clientes"
weight = 4
[languages.eus]
languageName = "Euskera"
languageNameShort = "eus"
weight = 4
[[languages.eus.menu.main]]
name = "Zerbitzuak"
url = "#servicios"
weight = 1
[[languages.eus.menu.main]]
name = "Manifestua"
url = "#manifiesto"
weight = 2
[[languages.eus.menu.main]]
name = "Nor gara"
url = "#somos"
weight = 3
[[languages.eus.menu.main]]
name = "Bezeroak"
url = "#clientes"
weight = 4
[params]
disableDisqusTypes = ["page"]
featherIconsCDN = true
mode = "auto"
subtitle = "Agencia de redacción. Everything is copy."
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/knadh/hugo-ink"
[[params.social]]
icon = "rss"
name = "RSS"
url = "/index.xml"
[taxonomies]
tag = "tags"
