---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Trabajos - Case Studies
  create: all
  match: "**/*"
- type: directory
  path: content/servicios
  label: Servicios
  create: all
  match: "**/*"
- type: directory
  path: content/clientes
  label: Clientes
  create: all
  match: "**/*"
- type: directory
  path: content/manifiesto
  label: Manifiesto
  create: all
  match: "**/*"
- type: directory
  path: content/somos
  label: Somos
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Datos portada - Activar Case Study
  create: all
  match: "*"
- type: document
  path: config.toml
  label: General Config
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
